import os
import re
import json
import logging
import tempfile
import subprocess
from pathlib import Path
from groq import Groq
from google import genai
from google.genai import types
import imageio_ffmpeg

from hook_learner import get_learning_context, get_high_and_low_scores_context, save_hook_decision

logger = logging.getLogger("AIHookFinder")
logging.basicConfig(level=logging.INFO, format="%(asctime)s - [%(levelname)s] - %(message)s")


def get_ffmpeg_exe() -> str:
    return imageio_ffmpeg.get_ffmpeg_exe()


def extract_audio_for_transcription(video_path: str, output_audio_path: str) -> bool:
    """Extracts lightweight 16kHz mono MP3 audio for Groq Whisper."""
    ffmpeg_exe = get_ffmpeg_exe()
    cmd = [
        ffmpeg_exe, "-y",
        "-i", video_path,
        "-vn",
        "-ac", "1",
        "-ar", "16000",
        "-b:a", "64k",
        output_audio_path
    ]
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    return res.returncode == 0 and os.path.exists(output_audio_path)


def transcribe_with_whisper(audio_path: str, api_key: str) -> list[dict]:
    """Transcribes audio using Groq whisper-large-v3 and returns segment list."""
    client = Groq(api_key=api_key)
    with open(audio_path, "rb") as f:
        transcription = client.audio.transcriptions.create(
            file=(os.path.basename(audio_path), f.read()),
            model="whisper-large-v3",
            response_format="verbose_json",
            timestamp_granularities=["segment"]
        )

    segments = []
    raw_segments = getattr(transcription, "segments", None) or []
    for seg in raw_segments:
        if isinstance(seg, dict):
            s_start = float(seg.get("start", 0.0))
            s_end = float(seg.get("end", 0.0))
            s_text = str(seg.get("text", "")).strip()
        else:
            s_start = float(getattr(seg, "start", 0.0))
            s_end = float(getattr(seg, "end", 0.0))
            s_text = str(getattr(seg, "text", "")).strip()

        if s_text:
            segments.append({
                "start": round(s_start, 2),
                "end": round(s_end, 2),
                "text": s_text
            })

    return segments


def analyze_segments_with_gemini(
    segments: list[dict],
    video_duration: float,
    gemini_api_key: str,
    target_platform: str = "tiktok"
) -> dict:
    """
    Analyzes speech segments with Google Gemini (gemini-3.6-flash).
    Includes continuous 1-10 gradient learning, platform targeting, and multimodal audio awareness.
    Explicitly prioritizes:
    1. Screams / Emotional Outbursts (Крики, вереск, шокові емоції, ААААА).
    2. Moments right before or during explosive laughter (Момент перед вибухом сміху, дикий чад/угар).
    3. Ridiculous funny fails / clutch quotes.
    Duration strictly 1.5s - 3.0s.
    """
    client = genai.Client(api_key=gemini_api_key)
    
    # Retrieve past rating history and high/low score ledger
    historical_high_scores, historical_low_scores = get_high_and_low_scores_context()

    prompt = f"""You are an elite viral video editor specializing in high-energy gaming and video highlights for {target_platform}.
Analyze the following transcribed spoken dialogue segments with timestamps:
{json.dumps(segments, ensure_ascii=False, indent=2)}

Total video duration: {video_duration:.2f} seconds.

### 🎯 TARGET PLATFORM: {target_platform}

### 🔤 SUBTITLE DETECTION DIRECTIVE (OCR) - [APPLIES TO ALL PLATFORMS]:
Visually analyze the video frames of your selected clip. Check if there are ALREADY prominent, hardcoded subtitles or text transcribing the speech on the screen.
- If you see existing subtitles baked into the video, set `has_hardcoded_subs: true`.
- If the screen is mostly free of transcription text, set `has_hardcoded_subs: false`.

### 🧲 DYNAMIC CTA (BAIT) DIRECTIVE:
Generate a Russian Call to Action (CTA) tailored strictly to the specified TARGET PLATFORM.

IF TARGET PLATFORM IS "youtube_shorts":
- Goal: Maximize Subscriptions and Comments via two separate timed badges.
- NO karambit video is used for YouTube Shorts.
- Timing 1 (~20s / 33% of video): Subscribe bait (e.g. "Улыбнулся? С тебя подписка!").
- Timing 2 (~50s / 80% of video): Comment bait (e.g. "А что думаешь ты? Пиши в комменты!").
- DO NOT use emojis in CTA text so typography stays crisp without missing font glyphs.

IF TARGET PLATFORM IS "tiktok":
- Goal: Maximize Saves / Bookmarks (Сохраненки).
- Animation points directly to the TikTok bookmark icon with a skin video overlay.
- STRICT MANDATORY TEXT: ALWAYS set `suggested_cta` strictly to: "Закинь в сохраненки, чтобы получить этот скин!" (Do not use any other phrase for TikTok).

### 1. MULTIMODAL & WHISPER FIX (CRITICAL)
The provided text transcript was generated by Whisper AI. WARNING: Whisper often ignores or deletes raw screams, desk smashes, and hysterical laughter, mistaking them for background noise. DO NOT rely solely on the text to find the emotional peak! You MUST actively listen to the raw audio track of the video. If you hear a massive rage scream or laugh that is MISSING from the transcript, USE IT as the hook anyway.

### 2. SCORING & COEFFICIENT LOGIC
Evaluate moments using a `viral_coefficient` (Scale 1.0 - 10.0). Balance the score using the following weights:
- Visual Action Score (Weight: 0.6): High-impact on-screen events (flicks, clutches, visual bugs, sudden deaths).
- Audio Emotion Score (Weight: 0.4): Extreme audio peaks (rage, screams, toxic reactions, hysterical laughter).

### 3. THE 1-10 GRADING MATRIX
The user strictly grades your hook and clip selection. Calibrate your choices according to this exact feedback matrix:
10 🌟: Exact energy and explosion. Perfect sync of on-screen action and off-screen rage.
9 🔥: Excellent hook choice. High emotional peaks.
8 ✨: Good choice, emulate this style.
7 👍: Acceptable, but try to find even more explosive timing.
6 👌: Needs more emotional intensity.
5 ⚖️: Too plain. Ordinary dialogue.
4 ⚠️: Lacks viral energy. Avoid calm dialogue.
3 ❌: Weak/Failed. User disliked this choice.
2 🚫: Monotonous dialogue. Scene merging violations. Strictly avoid.
1 ⛔️: CRITICAL FAILURE. NEVER repeat this. If speech is calm, fallback immediately to loudest audio/visual energy.

### 4. DYNAMIC MEMORY MODULE (USER CORRECTION LEDGER)
Below is the history of the user's most recent ratings. LEARN FROM THESE to avoid past mistakes and replicate successes:
{historical_high_scores}
{historical_low_scores}

CRITICAL HOOK SELECTION RULES:
1. **SCREAMS & EMOTIONAL PEAKS (Target 10/10 Rating)**: Loud screams, panic yells, sudden shouting ("АААА", "ТИ ШО РОБИШ", "ТА НУ НАФІГ"), hysterical laughter.
2. **BANAL DIALOGUE WARNING (Avoid 1-4/10 Ratings)**: If dialogue consists only of mundane, calm talk (like "ага", "ну", "тут можно..."), DO NOT treat it as a strong hook! Look for the most animated or energetic moment.
3. **DURATION CONSTRAINT**:
   - The hook duration (end_time - start_time) MUST strictly be between 1.5 and 3.0 seconds (maximum 3.0s).
   - It must capture the exact peak of emotion or punchline.

Respond ONLY with a JSON object in this exact schema:
{{
  "start_time": <float, start time in seconds>,
  "end_time": <float, end time in seconds>,
  "quote": "<exact spoken phrase or description of scream/laugh>",
  "visual_action_score": <int 1-10>,
  "audio_emotion_score": <int 1-10>,
  "viral_coefficient": <float 1.0-10.0>,
  "has_hardcoded_subs": <boolean, true if subtitles are baked in>,
  "suggested_cta": "<string, Russian call to action strictly adhering to TARGET PLATFORM directive>",
  "reason": "<short 1-sentence explanation in Ukrainian why this moment is chosen and how it aims for a 10/10 score>"
}}"""

    config = types.GenerateContentConfig(
        response_mime_type="application/json",
        system_instruction=f"You are a professional video editor identifying viral {target_platform} hooks calibrated to the user's 1-10 rating matrix and platform CTA rules. Always respond with valid JSON.",
        temperature=0.3
    )

    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt,
        config=config
    )

    content = response.text.strip()
    data = json.loads(content)

    start = float(data.get("start_time", data.get("start", 0.0)))
    end = float(data.get("end_time", data.get("end", start + 2.5)))
    quote = str(data.get("quote", "")).strip()
    reason = str(data.get("reason", "")).strip()
    vas = int(data.get("visual_action_score", 8))
    aes = int(data.get("audio_emotion_score", 8))
    vc = float(data.get("viral_coefficient", round(0.6 * vas + 0.4 * aes, 1)))
    has_hardcoded_subs = bool(data.get("has_hardcoded_subs", False))
    
    default_cta = "Хочешь также? Пиши в комменты 👇" if target_platform == "youtube_shorts" else "Закинь в сохраненки, чтобы получить этот скин!"
    suggested_cta = str(data.get("suggested_cta", default_cta)).strip()

    # Enforce constraints: duration between 1.5 and 3.0 seconds, within video bounds
    start = max(0.0, min(start, max(0.0, video_duration - 1.5)))
    if end <= start:
        end = min(video_duration, start + 2.5)

    duration = end - start
    if duration > 3.0:
        end = min(video_duration, start + 3.0)
    elif duration < 1.5 and (video_duration - start) >= 1.5:
        end = min(video_duration, start + 2.0)

    return {
        "start": round(start, 2),
        "end": round(end, 2),
        "start_time": round(start, 2),
        "end_time": round(end, 2),
        "duration": round(end - start, 2),
        "quote": quote,
        "reason": reason,
        "visual_action_score": vas,
        "audio_emotion_score": aes,
        "viral_coefficient": round(vc, 1),
        "has_hardcoded_subs": has_hardcoded_subs,
        "suggested_cta": suggested_cta,
        "target_platform": target_platform,
        "method": "gemini-3.6-flash"
    }


def find_audio_energy_peak(video_path: str, video_duration: float) -> dict:
    """Fallback: detects audio energy peak (loudest shout/shot/laughter) via FFmpeg."""
    ffmpeg_exe = get_ffmpeg_exe()
    cmd = [
        ffmpeg_exe, "-i", video_path,
        "-af", "asetnsamples=n=16000,astats=metadata=1:reset=1,ametadata=print:key=lavfi.astats.Overall.RMS_level",
        "-f", "null", "-"
    ]
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

    peak_time = 0.0
    max_db = -100.0
    current_time = 0.0

    for line in res.stderr.splitlines():
        t_match = re.search(r"pts_time:(\d+\.?\d*)", line)
        if t_match:
            current_time = float(t_match.group(1))
        db_match = re.search(r"lavfi\.astats\.Overall\.RMS_level=([-\d\.]+)", line)
        if db_match:
            try:
                db_val = float(db_match.group(1))
                if db_val > max_db and current_time < (video_duration - 0.5):
                    max_db = db_val
                    peak_time = current_time
            except ValueError:
                pass

    hook_duration = min(2.5, video_duration)
    start = max(0.0, peak_time - 0.8)
    if start + hook_duration > video_duration:
        start = max(0.0, video_duration - hook_duration)
    end = min(video_duration, start + hook_duration)

    return {
        "start": round(start, 2),
        "end": round(end, 2),
        "duration": round(end - start, 2),
        "quote": "🔊 Емоційний вигук / пік гучності у грі",
        "reason": f"Виявлено найгучніший сплеск звуку в геймплеї (пік на {peak_time:.2f}с, {max_db:.1f} dB)",
        "method": "audio_energy_peak"
    }


def find_best_hook(
    video_path: str,
    video_duration: float,
    groq_api_key: str,
    gemini_api_key: str,
    job_id: str = "",
    target_platform: str = "tiktok"
) -> dict:
    """
    Main hook detector:
    1. Extracts audio & transcribes using Groq whisper-large-v3.
    2. Analyzes transcription using Google Gemini (gemini-3.6-flash) with continuous 1-10 gradient matrix and target platform CTA.
    3. Saves decision awaiting user 1-10 rating.
    4. If no speech or error occurs, falls back to audio energy peak detection.
    """
    temp_audio = None
    segments = []
    try:
        with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as tmp:
            temp_audio = tmp.name

        logger.info(f"Extracting audio for Groq AI transcription from {video_path}...")
        if not extract_audio_for_transcription(video_path, temp_audio):
            raise RuntimeError("Failed to extract audio stream from video")

        logger.info("Transcribing audio with Groq whisper-large-v3...")
        segments = transcribe_with_whisper(temp_audio, groq_api_key)
        logger.info(f"Whisper transcription returned {len(segments)} speech segments")

        if segments:
            logger.info(f"Analyzing speech with Google Gemini for {target_platform}...")
            hook_result = analyze_segments_with_gemini(segments, video_duration, gemini_api_key, target_platform=target_platform)
            logger.info(f"AI Hook found with Gemini: {hook_result}")
            if job_id:
                save_hook_decision(job_id, segments, hook_result)
            return hook_result
        else:
            logger.info("No speech detected by Whisper. Falling back to audio peak energy analysis...")
            hook_result = find_audio_energy_peak(video_path, video_duration)
            if job_id:
                save_hook_decision(job_id, [], hook_result)
            return hook_result

    except Exception as e:
        logger.warning(f"AI hook detection failed ({e}). Falling back to audio peak detection...")
        try:
            hook_result = find_audio_energy_peak(video_path, video_duration)
            if job_id:
                save_hook_decision(job_id, segments, hook_result)
            return hook_result
        except Exception as fb_err:
            logger.error(f"Fallback energy detection failed ({fb_err}). Using start of video as hook.")
            dur = min(2.5, video_duration)
            fallback_hook = {
                "start": 0.0,
                "end": round(dur, 2),
                "duration": round(dur, 2),
                "quote": "Хук з початку відео",
                "reason": "Базовий хук перших секунд відео",
                "method": "default_fallback"
            }
            if job_id:
                save_hook_decision(job_id, segments, fallback_hook)
            return fallback_hook
    finally:
        if temp_audio and os.path.exists(temp_audio):
            try:
                os.remove(temp_audio)
            except Exception:
                pass
